export * from "./social";
export {
  AwsIcon,
  BashIcon,
  BloggerIcon,
  CppIcon,
  CanvaIcon,
  ClerkIcon,
  CloudRunIcon,
  CloudflareIcon,
  DrizzleOrmIcon,
  ExpressJsIcon,
  FigmaIcon,
  GeminiIcon,
  GitIcon,
  GithubIcon as GithubTechIcon,
  GoIcon,
  JqueryIcon,
  JavascriptIcon,
  JsonIcon,
  MongodbIcon,
  NestjsIcon,
  NextJsIcon,
  NodeJsIcon,
  NpmIcon,
  OpenaiIcon,
  PostgresqlIcon,
  PostmanIcon,
  PrismaIcon,
  PythonIcon,
  ReactHookFormIcon,
  ReactIcon,
  ReactQueryIcon,
  ShadcnUiIcon,
  StripeIcon,
  SupabaseIcon,
  TailwindCssIcon,
  TurborepoIcon,
  TypescriptIcon,
  VercelIcon,
  VertexAiIcon,
  ViteJsIcon,
  VscodeIcon,
  ZodIcon,
  ZustandIcon,
} from "./tech";
