import { PropsWithChildren } from 'react';

export function Typography({ children }: PropsWithChildren) {
  return (
    <div className="prose prose-zinc dark:prose-invert max-w-none prose-lg prose-headings:font-light prose-headings:tracking-tight prose-headings:scroll-m-20 prose-h1:text-4xl prose-h1:mb-8 prose-h1:mt-12 prose-h2:text-3xl prose-h2:mb-6 prose-h2:mt-10 prose-h3:text-2xl prose-h3:mb-4 prose-h3:mt-8 prose-h4:text-xl prose-h4:mb-3 prose-h4:mt-6 prose-p:font-light prose-p:leading-relaxed prose-p:text-zinc-700 dark:prose-p:text-zinc-300 prose-p:mb-6 prose-a:text-zinc-900 dark:prose-a:text-zinc-100 prose-a:underline-offset-4 prose-a:decoration-zinc-400 dark:prose-a:decoration-zinc-600 hover:prose-a:decoration-zinc-600 dark:hover:prose-a:decoration-zinc-400 prose-a:transition-colors prose-a:duration-300 prose-strong:text-zinc-900 dark:prose-strong:text-zinc-100 prose-strong:font-medium prose-em:text-zinc-800 dark:prose-em:text-zinc-200 prose-blockquote:border-zinc-300 dark:prose-blockquote:border-zinc-700 prose-blockquote:bg-zinc-50 dark:prose-blockquote:bg-zinc-900 prose-blockquote:px-6 prose-blockquote:py-4 prose-blockquote:font-light prose-blockquote:italic prose-blockquote:text-zinc-700 dark:prose-blockquote:text-zinc-300 prose-code:font-mono prose-code:text-sm prose-code:bg-zinc-100 dark:prose-code:bg-zinc-800 prose-code:text-zinc-900 dark:prose-code:text-zinc-100 prose-code:px-1.5 prose-code:py-0.5 prose-code:border prose-code:border-zinc-200 dark:prose-code:border-zinc-700 prose-code:before:content-none prose-code:after:content-none prose-pre:bg-zinc-50 dark:prose-pre:bg-zinc-900 prose-pre:border prose-pre:border-zinc-200 dark:prose-pre:border-zinc-800 prose-img:border prose-img:border-zinc-200 dark:prose-img:border-zinc-800 prose-img:my-6 prose-hr:border-zinc-300 dark:prose-hr:border-zinc-700 prose-hr:my-8 prose-ul:mb-6 prose-ol:mb-6 prose-li:text-zinc-700 dark:prose-li:text-zinc-300 prose-li:font-light prose-li:leading-relaxed prose-li:mb-2 prose-table:border prose-table:border-zinc-200 dark:prose-table:border-zinc-800 prose-th:bg-zinc-50 dark:prose-th:bg-zinc-900 prose-th:border prose-th:border-zinc-200 dark:prose-th:border-zinc-800 prose-th:px-4 prose-th:py-2 prose-th:text-left prose-th:font-mono prose-th:text-xs prose-th:uppercase prose-th:tracking-wide prose-th:text-zinc-700 dark:prose-th:text-zinc-300 prose-td:border prose-td:border-zinc-200 dark:prose-td:border-zinc-800 prose-td:px-4 prose-td:py-2 prose-td:text-zinc-700 dark:prose-td:text-zinc-300">
      {children}
    </div>
  );
}
