import type { DeveloperConfig } from "@/types";

export const DeveloperDetails: DeveloperConfig = {
  name: "Nabin Khair",
  initials: "NK",
  designation: "Fullstack Developer",
  portfolio: "https://nabinkhair.com.np",
  email: "nabinkhair12@gmail.com",
  bio: "Hi World, I'm Nabin Khair, a fullstack developer from Nepal with 2+ years of experience building performant, accessible web applications. I specialize in React, Next.js and TypeScript, and I focus on creating maintainable code, thoughtful UX, and reliable backends.",
  avatar: "/nabin_khair.webp",
  resume: "https://nabinkhair.com.np/nabin_khair.pdf",
  socialLinks: [
    {
      name: "LinkedIn",
      url: "https://www.linkedin.com/in/nabinkhair42/",
      icon: "/social/linkedin.svg",
      hasDarkIcon: false,
      handle: "nabinkhair42",
    },
    {
      name: "GitHub",
      url: "https://github.com/nabinkhair42",
      icon: "/social/github.svg",
      hasDarkIcon: true,
      handle: "nabinkhair42",
    },
    {
      name: "Twitter",
      url: "https://twitter.com/khairnabin",
      icon: "/social/twitter.svg",
      hasDarkIcon: false,
      handle: "khairnabin",
    },
    {
      name: "Instagram",
      url: "https://www.instagram.com/nabinkhair2",
      icon: "/social/instagram.svg",
      hasDarkIcon: false,
      handle: "nabinkhair2",
    },
  ],
  location: {
    city: "Dharan",
    country: "Nepal",
  },
  seo: {
    title: "Nabin Khair | Full Stack Developer from Nepal",
    description:
      "Nabin Khair is a Full Stack Developer from Nepal specializing in React, Next.js, and TypeScript. Building accessible, high-performance web applications.",
    keywords: [
      "Nabin Khair",
      "nabinkhair",
      "nabinkhair42",
      "Full Stack Developer",
      "Full Stack Developer Nepal",
      "React Developer Nepal",
      "Next.js Developer",
      "TypeScript Developer",
      "MERN Stack Developer",
      "Web Developer Nepal",
      "Software Engineer Nepal",
      "Freelance Developer Nepal",
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "JavaScript",
      "Dharan Developer",
    ],
  },
  education: [
    {
      degree: "Bachelor of Computer Engineering",
      institution: "IOE Purwanchal Campus",
      logo: "/education/ioepc.png",
      startDate: "2023",
      endDate: "2027",
      location: "Dharan, Nepal",
    },
    {
      degree: "Higher Secondary Education (10+2)",
      institution: "Galaxy Secondary School",
      logo: "/education/galaxy.png",
      startDate: "2021",
      endDate: "2023",
      location: "Dhangadhi, Nepal",
    },
  ],
};
