import {
  AwsIcon,
  ClerkIcon,
  CloudflareIcon,
  CloudRunIcon,
  ExpressJsIcon,
  FigmaIcon,
  GeminiIcon,
  GoIcon,
  MongodbIcon,
  NestjsIcon,
  NextJsIcon,
  PostgresqlIcon,
  PostmanIcon,
  ReactIcon,
  ReactQueryIcon,
  ShadcnUiIcon,
  StripeIcon,
  SupabaseIcon,
  TailwindCssIcon,
  TypescriptIcon,
  VercelIcon,
  VertexAiIcon,
  ZodIcon,
} from "@/icons/tech";
import type { Experience } from "@/types";

export const ExperienceData: Experience[] = [
  {
    company: "Mersel AI",
    logo: "/company/mersel-ai.png",
    designation: "Forward Deployed Engineer",
    type: "Full-time",
    startDate: "Nov 2025",
    endDate: "Present",
    isCurrent: true,
    description: [
      "Design and develop scalable web AI powered video generation platform.",
      "Implement robust backend services and APIs to support AI functionalities.",
      "Integrate cross-platform AI models into the platform.",
      "Optimize application performance and ensure seamless user experience.",
      "Design optimal pipelines for various video generation use-cases.",
    ],
    skills: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Express.js", icon: ExpressJsIcon },
      { name: "Supabase", icon: SupabaseIcon },
      { name: "Vertex", icon: VertexAiIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "Gemini", icon: GeminiIcon },
      { name: "Cloud Run", icon: CloudRunIcon },
      { name: "Go", icon: GoIcon },
      { name: "Stripe", icon: StripeIcon },
    ],
  },
  {
    company: "Tulio Health",
    logo: "/company/tulio-health.svg",
    designation: "Software Engineer",
    type: "Contract",
    startDate: "Aug 2025",
    endDate: "Dec 2025",
    isCurrent: false,
    description: [
      "Developed AI-powered healthcare dashboard and playground, enhancing doctor and patient interactions.",
      "Implemented robust authentication and authorization mechanisms using Clerk",
    ],
    skills: [
      { name: "Clerk", icon: ClerkIcon },
      { name: "Nest.js", icon: NestjsIcon },
      { name: "Next.js", icon: NextJsIcon },
      { name: "Postman", icon: PostmanIcon },
      { name: "PostgreSQL", icon: PostgresqlIcon },
      { name: "React.js", icon: ReactIcon },
      { name: "React Query", icon: ReactQueryIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    company: "Truly Care",
    logo: "/company/truly-care.webp",
    designation: "Frontend Developer",
    type: "Contract",
    startDate: "Jun 2025",
    endDate: "Aug 2025",
    isCurrent: false,
    description: [
      "Improved the design pattern of the existing codebase for better maintainability and scalability.",
      "Developed performance optimized onboarding forms with better user interaction.",
      "Collaborated with backend developers to integrate RESTful APIs and ensure seamless functionality.",
    ],
    skills: [
      { name: "Clerk", icon: ClerkIcon },
      { name: "Express.js", icon: ExpressJsIcon },
      { name: "Postman", icon: PostmanIcon },
      { name: "React.js", icon: ReactIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    company: "FinFox",
    logo: "/company/fin-fox.svg",
    designation: "Frontend Developer and UI/UX Designer",
    type: "Full-time",
    startDate: "May 2025",
    endDate: "Aug 2025",
    isCurrent: false,
    description: [
      "Led the frontend development and UI/UX design for a fintech SaaS platform, enhancing user experience and engagement.",
      "Worked closely with backend developers to integrate APIs and ensure seamless functionality.",
    ],
    skills: [
      { name: "Figma", icon: FigmaIcon },
      { name: "Next.js", icon: NextJsIcon },
      { name: "React.js", icon: ReactIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "TypeScript", icon: TypescriptIcon },
    ],
  },

  {
    company: "Uncle Sams Tech",
    logo: "/company/ust.webp",
    designation: "Web Developer",
    type: "Part-time",
    startDate: "Mar 2024",
    endDate: "May 2025",
    isCurrent: false,
    description: [
      "Developed strong backend for short videos sharing mobile application.",
      "Improved webapp performance and improved SEO using best practices.",
      "Worked on multiple web development projects for clients with diverse requirements.",
      "Designed UI/UX mockups and prototypes multiple mobile and web applications.",
    ],
    skills: [
      { name: "AWS", icon: AwsIcon },
      { name: "Cloudflare", icon: CloudflareIcon },
      { name: "Express.js", icon: ExpressJsIcon },
      { name: "Figma", icon: FigmaIcon },
      { name: "MongoDB", icon: MongodbIcon },
      { name: "Next.js", icon: NextJsIcon },
      { name: "Postman", icon: PostmanIcon },
      { name: "React.js", icon: ReactIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
];
