import {
  AwsIcon,
  ClerkIcon,
  CloudflareIcon,
  CloudRunIcon,
  ExpressJsIcon,
  FigmaIcon,
  GeminiIcon,
  GoIcon,
  MongodbIcon,
  NestjsIcon,
  NextJsIcon,
  PostgresqlIcon,
  PostmanIcon,
  ReactIcon,
  ReactQueryIcon,
  ShadcnUiIcon,
  StripeIcon,
  SupabaseIcon,
  TailwindCssIcon,
  TypescriptIcon,
  VercelIcon,
  VertexAiIcon,
  ZodIcon,
} from "@/icons/tech";
import type { Experience } from "@/types";

export const ExperienceData: Experience[] = [
  {
    company: "Mersel AI",
    logo: "/company/mersel-ai.png",
    designation: "Forward Deployed Engineer",
    type: "Full-time",
    startDate: "Nov 2025",
    endDate: "Jul 2026",
    isCurrent: false,
    description: [
      "Designed and shipped Mersel's GEO platform from scratch across 5 production subsystems: a Cloudflare edge worker, a Python FastAPI LLM service, a multi-tenant Payload CMS, a scheduled job worker, and a Next.js dashboard.",
      "Built citation monitoring across 6 AI search surfaces (ChatGPT, Gemini, Claude, Perplexity, Google AI Overview, AI Mode) with per-platform concurrency control.",
      "Own deployments and live debugging across Cloudflare, GCP, and Railway.",
    ],
    skills: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Express.js", icon: ExpressJsIcon },
      { name: "Supabase", icon: SupabaseIcon },
      { name: "Vertex", icon: VertexAiIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "Gemini", icon: GeminiIcon },
      { name: "Cloud Run", icon: CloudRunIcon },
      { name: "Go", icon: GoIcon },
      { name: "Stripe", icon: StripeIcon },
    ],
  },
  {
    company: "Tulio Health",
    logo: "/company/tulio-health.svg",
    designation: "Software Engineer",
    type: "Contract",
    startDate: "Aug 2025",
    endDate: "Dec 2025",
    isCurrent: false,
    description: [
      "Optimized performance across the AI healthcare dashboard and prompt playground used by doctors and patients.",
      "Set up authentication and authorization with Clerk.",
      "Built the React components and integrated REST APIs for the clinical workflows.",
    ],
    skills: [
      { name: "Clerk", icon: ClerkIcon },
      { name: "Nest.js", icon: NestjsIcon },
      { name: "Next.js", icon: NextJsIcon },
      { name: "Postman", icon: PostmanIcon },
      { name: "PostgreSQL", icon: PostgresqlIcon },
      { name: "React.js", icon: ReactIcon },
      { name: "React Query", icon: ReactQueryIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    company: "Truly Care",
    logo: "/company/truly-care.webp",
    designation: "Frontend Developer",
    type: "Contract",
    startDate: "Jun 2025",
    endDate: "Aug 2025",
    isCurrent: false,
    description: [
      "Refactored the existing frontend so the codebase was easier to extend and maintain.",
      "Built the multi-step onboarding forms with a focus on speed and a smoother user flow.",
      "Wired the forms to the REST API working with the backend team.",
    ],
    skills: [
      { name: "Clerk", icon: ClerkIcon },
      { name: "Express.js", icon: ExpressJsIcon },
      { name: "Postman", icon: PostmanIcon },
      { name: "React.js", icon: ReactIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    company: "FinFox",
    logo: "/company/fin-fox.svg",
    designation: "Frontend Developer & UI/UX Designer",
    type: "Full-time",
    startDate: "May 2025",
    endDate: "Aug 2025",
    isCurrent: false,
    description: [
      "Led the frontend and UI/UX design for a fintech SaaS platform.",
      "Build the frontend with Next.js, TypeScript, and Tailwind CSS.",
    ],
    skills: [
      { name: "Figma", icon: FigmaIcon },
      { name: "Next.js", icon: NextJsIcon },
      { name: "React.js", icon: ReactIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "TypeScript", icon: TypescriptIcon },
    ],
  },

  {
    company: "Uncle Sams Tech",
    logo: "/company/ust.webp",
    designation: "Web Developer",
    type: "Part-time",
    startDate: "Mar 2024",
    endDate: "May 2025",
    isCurrent: false,
    description: [
      "Built backend services for a short-form video sharing mobile app.",
      "Improved web performance and SEO across several of the company's products.",
      "Designed UI/UX prototypes in Figma for both mobile and web.",
    ],
    skills: [
      { name: "AWS", icon: AwsIcon },
      { name: "Cloudflare", icon: CloudflareIcon },
      { name: "Express.js", icon: ExpressJsIcon },
      { name: "Figma", icon: FigmaIcon },
      { name: "MongoDB", icon: MongodbIcon },
      { name: "Next.js", icon: NextJsIcon },
      { name: "Postman", icon: PostmanIcon },
      { name: "React.js", icon: ReactIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
];
