import {
  Astro,
  AwsIcon,
  BashIcon,
  BloggerIcon,
  CanvaIcon,
  CloudflareIcon,
  DrizzleOrmIcon,
  ExpressJsIcon,
  GithubIcon,
  JavascriptIcon,
  JqueryIcon,
  JsonIcon,
  MongodbIcon,
  NextJsIcon,
  NodeJsIcon,
  NpmIcon,
  PostgresqlIcon,
  PostmanIcon,
  PrismaIcon,
  PythonIcon,
  ReactHookFormIcon,
  ReactQueryIcon,
  ShadcnUiIcon,
  StripeIcon,
  SwiftIcon,
  TailwindCssIcon,
  TurborepoIcon,
  TypescriptIcon,
  VercelIcon,
  VscodeIcon,
  ZodIcon,
} from "@/icons/tech";
import type { Projects } from "@/types";

export const ProjectsData: Projects[] = [
  {
    icon: "/projects/tallwatch.svg",
    title: "TallWatch",
    tagline: "Detect Downtime before your users do",
    description:
      "Tallwatch monitors your sites and APIs from multiple regions, alerts the right people when something breaks",
    liveLink: "https://tallwatch.com",
    techStack: [
      { name: "AWS", icon: AwsIcon },
      { name: "Cloudflare", icon: CloudflareIcon },
      { name: "Nest.js", icon: NextJsIcon },
      { name: "Next.js", icon: NextJsIcon },
      { name: "PostgreSQL", icon: PostgresqlIcon },
      { name: "React Query", icon: ReactQueryIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    icon: "/projects/git-chat.svg",
    title: "GitChat",
    tagline: "Chat-based GitHub Client powered by AI",
    description:
      "A chat-based GitHub client. The LLM browses repos, reviews PRs, and triggers CI workflows through tool calls, and asks for confirmation before anything destructive. Built solo. Live at git.nabinkhair.com.np.",
    liveLink: "https://git.nabinkhair.com.np",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Vercel AI SDK", icon: VercelIcon },
      { name: "GitHub API", icon: GithubIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    icon: "/projects/assets-man.svg",
    title: "Assets Man",
    tagline: "A self-hosted, open-source Google Drive alternative.",
    description:
      "An open-source, self-hosted alternative to Google Drive. File storage, sharing, and asset organization for teams that want to keep their files on their own infrastructure.",
    liveLink: "https://assets-man.nabinkhair.com.np",
    repo: "https://github.com/nabinkhair42/assets-man",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "PostgreSQL", icon: PostgresqlIcon },
      { name: "Drizzle ORM", icon: DrizzleOrmIcon },
      { name: "Express", icon: ExpressJsIcon },
      { name: "Turborepo", icon: TurborepoIcon },
      { name: "AWS S3", icon: AwsIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    icon: "/projects/flow-mint.svg",
    title: "FlowMint",
    tagline: "Diagrams Made Effortless",
    description:
      "Turns a natural-language prompt into a shareable diagram. The LLM does the parsing, the renderer turns it into something you can paste anywhere.",
    liveLink: "https://flow.nabinkhair.com.np",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "MongoDB", icon: MongodbIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "React Query", icon: ReactQueryIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Stripe", icon: StripeIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    icon: "/projects/better-form.svg",
    title: "Better Form",
    tagline: "DX-First Dynamic Form Builder for React & Next.js",
    description:
      "A type-safe dynamic form builder for React and Next.js. Schema-driven, zero-config, designed around how developers actually want to build forms. Open source.",
    liveLink: "https://better-form.nabinkhair.com.np",
    repo: "https://github.com/nabinkhair42/better-form",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Zod", icon: ZodIcon },
      { name: "React Hook Form", icon: ReactHookFormIcon },
    ],
  },
  {
    icon: "/projects/fastly.svg",
    title: "Fastly",
    tagline: "SaaS Starter Kit",
    description:
      "A SaaS starter kit for solo developers and startups, with JWT-based authentication and authorization, a user management dashboard, image uploading via Uploadthing, and built-in Vercel deployment.",
    liveLink: "https://fastly.nabinkhair.com.np",
    repo: "https://github.com/nabinkhair42/fastly",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "MongoDB", icon: MongodbIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "React Query", icon: ReactQueryIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },

  {
    icon: "/projects/pestjs.svg",
    title: "PEST.js",
    tagline: "CLI to Scaffold Production-Ready Express 5 + TypeScript APIs",
    description:
      "A CLI tool that scaffolds production-grade Express 5 + TypeScript projects with a single command. Interactive prompts configure the database ORM (Prisma, Drizzle, TypeORM), Docker, and package manager, generating a complete stack with Helmet, CORS, Pino logging, Zod validation, rate limiting, Jest + Supertest, ESLint, Prettier, and Husky. Ships as a monorepo with a docs website built on Next.js, fumadocs, and a custom Structural Grid design system.",
    liveLink: "https://pestjs.vercel.app",
    repo: "https://github.com/nabinkhair42/pest-js",
    techStack: [
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Node.js", icon: NodeJsIcon },
      { name: "Express", icon: ExpressJsIcon },
      { name: "Next.js", icon: NextJsIcon },
      { name: "NPM Package", icon: NpmIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Zod", icon: ZodIcon },
      { name: "Prisma", icon: PrismaIcon },
      { name: "Drizzle ORM", icon: DrizzleOrmIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Vercel", icon: VercelIcon },
    ],
  },
  {
    icon: "/projects/skills.svg",
    title: "nk-skills",
    tagline: "Reusable agent skills for product engineers",
    description:
      "Reusable engineering patterns I use as a product engineer, packaged as installable agent skills. Includes a 9-layer Next.js product stack, an optimistic cache pattern for React Query, and a structural-grid design system in the spirit of Linear and Vercel.",
    liveLink: "https://skills.nabinkhair.com.np",
    repo: "https://github.com/nabinkhair42/nk-skills",
    techStack: [
      { name: "Astro", icon: Astro },
      { name: "JavaScript", icon: JavascriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Bash", icon: BashIcon },
    ],
  },
  {
    icon: "/projects/pro-mcp.svg",
    title: "Pro MCP",
    tagline: "Registry of MCP Servers",
    liveLink: "https://promcp.nabinkhair.com.np",
    description:
      "A community-driven registry for MCP servers. Discovery, search, and integration patterns for the Model Context Protocol ecosystem.",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "Python", icon: PythonIcon },
      { name: "JavaScript", icon: JavascriptIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
    ],
  },
  {
    icon: "/projects/vtheme.svg",
    title: "VTheme",
    tagline: "Perfect VS Code Theme",
    liveLink: "https://vthemes.nabinkhair.com.np/",
    repo: "https://github.com/nabinkhair42/vtheme",
    description:
      "A professionally designed VS Code color theme based on advanced color theory principles, with carefully crafted colors that enhance the coding experience and reduce eye strain. Over 1200+ active users worldwide.",
    techStack: [
      { name: "JSON", icon: JsonIcon },
      { name: "VS Code", icon: VscodeIcon },
    ],
  },

  {
    icon: "/projects/nepali-educate.png",
    title: "Nepali Educate",
    tagline: "Online Learning Platform",
    description:
      "An online learning platform offering high-quality study notes for grade 11 and 12 students, with a user-friendly interface for easy access to study materials. Trusted by over 50,000 students across Nepal and serving over 100k monthly visitors.",
    liveLink: "https://nepalieducate.com",
    techStack: [
      { name: "Jquery", icon: JqueryIcon },
      { name: "Blogger", icon: BloggerIcon },
      { name: "Canva", icon: CanvaIcon },
    ],
  },
  {
    icon: "/projects/datalens.svg",
    title: "DataLens",
    tagline: "The web-native, collaborative database IDE",
    description:
      "A web-based, collaborative database IDE for effortless data exploration and management. Connect to any database with a simple connection string and intuitive UI, collaborate in real time by sharing queries, results, and insights, and visualize data with built-in charts and multi-format exports.",
    liveLink: "https://datalens.nabinkhair.com.np",
    repo: "https://github.com/nabinkhair42/datalens",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Zod", icon: ZodIcon },
      { name: "React Query", icon: ReactQueryIcon },
      { name: "PostgreSQL", icon: PostgresqlIcon },
      { name: "Drizzle ORM", icon: DrizzleOrmIcon },
    ],
  },
  {
    icon: "/projects/juju.png",
    title: "Juju Connect",
    tagline: "Your Story, Your Stage",
    liveLink: "https://jujuconnect.com",
    description:
      "Designed and built the backend architecture for the platform, hosting and deploying all services on AWS and Cloudflare. Developed and tested APIs with Postman while collaborating with cross-functional teams to define, design, and ship new features.",
    techStack: [
      { name: "Node.js", icon: NodeJsIcon },
      { name: "Express.js", icon: ExpressJsIcon },
      { name: "MongoDB", icon: MongodbIcon },
      { name: "AWS", icon: AwsIcon },
      { name: "Cloudflare", icon: CloudflareIcon },
      { name: "Postman", icon: PostmanIcon },
    ],
  },

  {
    icon: "/projects/env-store.svg",
    title: "ENV Store",
    tagline: "Never Lose Your .env Again",
    description:
      "Securely manage and sync environment variables across devices with AES-256-GCM encryption. Sign in via GitHub OAuth without password management, import existing .env files or export configurations as standard .env format, and organize variables by project and environment across development, staging, and production.",
    liveLink: "https://envstore.nabinkhair.com.np",
    repo: "https://github.com/nabinkhair42/env-store",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "MongoDB", icon: MongodbIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "GitHub API", icon: GithubIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
    ],
  },
  {
    icon: "/projects/your-git.svg",
    title: "YourGit",
    tagline: "GitHub Profile Stats Summary",
    liveLink: "https://yourgit.vercel.app/",
    description:
      "Visualize any GitHub profile's contribution stats in a clean, shareable summary card showing repos, stars, followers, and contribution streaks at a glance.",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Stripe", icon: StripeIcon },
    ],
  },
  {
    icon: "/projects/nepali-calendar.svg",
    title: "Nepali Calendar",
    tagline: "Bikram Sambat in your macOS menu bar",
    description:
      "A quiet macOS menu bar app for Bikram Sambat with festivals, public holidays, and a popover that stays out of the way. Shows BS and AD together with Nepali or English labels and keyboard shortcuts for fast month navigation. Built for macOS 14 or later with no accounts, no telemetry, and a SHA-256 verified installer, distributed through the website and GitHub releases with a one-command installer for the latest build.",
    liveLink: "https://calendar.nabinkhair.com.np/",
    repo: "https://github.com/nabinkhair42/nepali-calendar",
    techStack: [
      { name: "Swift", icon: SwiftIcon },
      { name: "Bash", icon: BashIcon },
    ],
  },
];
