import type { Projects } from "@/types";

export const ProjectsData: Projects[] = [
  {
    icon: "/projects/better-form.svg",
    title: "Better Form",
    tagline: "DX-First Dynamic Form Builder for React & Next.js",
    description: [
      "A next-generation developer-first dynamic form builder for React and Next.js",
      "Build powerful forms with drag & drop, live preview, and code export functionality",
      "Type-safe form building with TypeScript, Zod validation, and React Hook Form integration",
      "Beautiful UI built with shadcn/ui components and Tailwind CSS",
    ],
    liveLink: "https://better-form.nabinkhair.com.np",
    techStack: [
      { name: "Next.js", icon: "/tech-icon/nextjs.svg", hasDarkIcon: true },
      { name: "TypeScript", icon: "/tech-icon/typescript.svg" },
      { name: "Tailwind CSS", icon: "/tech-icon/tailwindcss.svg" },
      { name: "Vercel", icon: "/tech-icon/vercel.svg", hasDarkIcon: true },
      { name: "shadcn/ui", icon: "/tech-icon/shadcnui.svg", hasDarkIcon: true },
      { name: "Zod", icon: "/tech-icon/zod.svg" },
      { name: "React Hook Form", icon: "/tech-icon/react-hook-form.svg" },
    ],
  },
  {
    icon: "/projects/fastly.png",
    title: "Fastly",
    tagline: "SaaS Starter Kit",
    description: [
      "A SaaS starter kit for solo developers and startups.",
      "JWT Based Authentication and Authorization.",
      "User Management Dashboard",
      "Image Uploading with Uploadthing",
      "Builtin Vercel Deployment",
    ],
    liveLink: "https://fastly.nabinkhair.com.np",
    repo: "https://github.com/nabinkhair42/fastly",
    techStack: [
      { name: "Next.js", icon: "/tech-icon/nextjs.svg", hasDarkIcon: true },
      { name: "TypeScript", icon: "/tech-icon/typescript.svg" },
      { name: "Tailwind CSS", icon: "/tech-icon/tailwindcss.svg" },
      { name: "MongoDB", icon: "/tech-icon/mongodb.svg" },
      { name: "Vercel", icon: "/tech-icon/vercel.svg", hasDarkIcon: true },
      { name: "React Query", icon: "/tech-icon/reactquery.svg" },
      { name: "shadcn/ui", icon: "/tech-icon/shadcnui.svg", hasDarkIcon: true },
      { name: "Zod", icon: "/tech-icon/zod.svg" },
    ],
  },
  {
    icon: "/projects/vtheme.svg",
    title: "VTheme",
    tagline: "Perfect VS Code Theme",
    liveLink: "https://vthemes.nabinkhair.com.np/",
    repo: "https://github.com/nabinkhair42/vtheme",
    description: [
      "Over 1200+ active users worldwide.",
      "Carefully crafted colors that enhance coding experience and reduce eye strain.",
      "A professionally designed color theme based on advanced color theory principles.",
    ],
    techStack: [
      { name: "JSON", icon: "/tech-icon/json.svg" },
      { name: "VS Code", icon: "/tech-icon/vscode.svg" },
    ],
  },
  {
    icon: "/projects/pro-mcp.svg",
    title: "Pro MCP",
    tagline: "Registry of MCP Servers",
    liveLink: "https://promcp.nabinkhair.com.np",
    description: [
      "Over 4200+ MCP servers listed from around the world.",
      "Custom Server Listing Website with auto scraping of server information.",
      "User can search and upload servers information",
      "User-friendly interface for easy navigation and access to server information.",
    ],
    techStack: [
      { name: "Next.js", icon: "/tech-icon/nextjs.svg", hasDarkIcon: true },
      { name: "Python", icon: "/tech-icon/python.svg" },
      { name: "JavaScript", icon: "/tech-icon/js.svg" },
      { name: "TypeScript", icon: "/tech-icon/typescript.svg" },
      { name: "Tailwind CSS", icon: "/tech-icon/tailwindcss.svg" },
      { name: "Vercel", icon: "/tech-icon/vercel.svg", hasDarkIcon: true },
      { name: "shadcn/ui", icon: "/tech-icon/shadcnui.svg", hasDarkIcon: true },
    ],
  },
  {
    icon: "/projects/nepali-educate.png",
    title: "Nepali Educate",
    tagline: "Online Learning Platform",
    description: [
      "An online learning platform offering a high quality study notes for students of grade  11 and 12",
      "User-friendly interface for easy navigation and access to study materials.",
      "Trusted by over 50,000 students across Nepal.",
      "Over 100k monthly visitors",
    ],
    liveLink: "https://nepalieducate.com",
    techStack: [
      { name: "Jquery", icon: "/tech-icon/jquery.svg" },
      { name: "Blogger", icon: "/tech-icon/blogger.svg" },
      { name: "Canva", icon: "/tech-icon/canva.svg" },
    ],
  },

  {
    icon: "/projects/juju.png",
    title: "Juju Connect",
    tagline: "Your Story, Your Stage",
    liveLink: "https://jujuconnect.com",
    description: [
      "Work on writing and designing the Backend of the Platform",
      "Hosted and Deployed entire services on AWS and Cloudflare",
      "Tested and developed APIs using Postman",
      "Collaborated with cross-functional teams to define, design, and ship new features",
    ],
    techStack: [
      { name: "Node.js", icon: "/tech-icon/nodejs.svg" },
      { name: "Express.js", icon: "/tech-icon/expressjs.svg" },
      { name: "MongoDB", icon: "/tech-icon/mongodb.svg" },
      { name: "AWS", icon: "/tech-icon/aws.svg", hasDarkIcon: true },
      { name: "Cloudflare", icon: "/tech-icon/cloudflare.svg" },
      { name: "Postman", icon: "/tech-icon/postman.svg" },
    ],
  },
  {
    icon: "/projects/flow-mint.png",
    title: "FlowMint",
    tagline: "Diagrams Made Effortless",
    description: [
      "A powerful diagramming tool for understanding and visualizing complex ideas.",
      "Create diagrams from simple text prompts using Gemini AI",
      "Export diagrams in multiple formats including PNG, SVG",
      "User authentication and management with JWT",
    ],
    liveLink: "https://flow.nabinkhair.com.np",
    techStack: [
      { name: "Next.js", icon: "/tech-icon/nextjs.svg", hasDarkIcon: true },
      { name: "TypeScript", icon: "/tech-icon/typescript.svg" },
      { name: "Tailwind CSS", icon: "/tech-icon/tailwindcss.svg" },
      { name: "MongoDB", icon: "/tech-icon/mongodb.svg" },
      { name: "Vercel", icon: "/tech-icon/vercel.svg", hasDarkIcon: true },
      { name: "React Query", icon: "/tech-icon/reactquery.svg" },
      { name: "shadcn/ui", icon: "/tech-icon/shadcnui.svg", hasDarkIcon: true },
      { name: "Stripe", icon: "/tech-icon/stripe.svg" },
      { name: "Zod", icon: "/tech-icon/zod.svg" },
    ],
  },
  {
    icon: "/tech-icon/nextjs.svg",
    title: "YourGit",
    tagline: "GitHub Profile Stats Summary",
    liveLink: "https://yourgit.vercel.app/",
    description: [],
    techStack: [
      { name: "Next.js", icon: "/tech-icon/nextjs.svg", hasDarkIcon: true },
      { name: "TypeScript", icon: "/tech-icon/typescript.svg" },
      { name: "Tailwind CSS", icon: "/tech-icon/tailwindcss.svg" },
      { name: "Vercel", icon: "/tech-icon/vercel.svg", hasDarkIcon: true },
      { name: "shadcn/ui", icon: "/tech-icon/shadcnui.svg", hasDarkIcon: true },
      { name: "Stripe", icon: "/tech-icon/stripe.svg" },
    ],
  },
];
