import {
  AwsIcon,
  BloggerIcon,
  CanvaIcon,
  CloudflareIcon,
  DrizzleOrmIcon,
  ExpressJsIcon,
  GithubIcon,
  JavascriptIcon,
  JqueryIcon,
  JsonIcon,
  MongodbIcon,
  NextJsIcon,
  NodeJsIcon,
  NpmIcon,
  PostmanIcon,
  PostgresqlIcon,
  PrismaIcon,
  PythonIcon,
  ReactHookFormIcon,
  ReactQueryIcon,
  ShadcnUiIcon,
  StripeIcon,
  TailwindCssIcon,
  TurborepoIcon,
  TypescriptIcon,
  VercelIcon,
  VscodeIcon,
  ZodIcon,
} from "@/icons/tech";
import type { Projects } from "@/types";

export const ProjectsData: Projects[] = [
  {
    icon: "/projects/git-chat.svg",
    title: "GitChat",
    tagline: "Chat-based GitHub Client powered by AI",
    description: [
      "Chat with any GitHub repo: browse, review, and manage without leaving the conversation.",
      "96 agentic tools covering the full GitHub surface: PRs, issues, CI/CD, security, and more.",
      "Super Mode chains multi-step workflows end-to-end with zero manual confirmation.",
      "Multi-provider AI support with model switching, mentions, and a command palette.",
    ],
    liveLink: "https://git.nabinkhair.com.np",
    // repo: "https://github.com/nabinkhair42/git-chat",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel AI SDK", icon: VercelIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "GitHub API", icon: GithubIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    icon: "/projects/pestjs.png",
    title: "PEST.js",
    tagline: "CLI to Scaffold Production-Ready Express 5 + TypeScript APIs",
    description: [
      "A CLI tool that scaffolds production-grade Express 5 + TypeScript projects with a single command.",
      "Interactive prompts for project config: database ORM (Prisma, Drizzle, TypeORM), Docker, package manager, and more.",
      "Generates a complete stack: Express 5, Helmet, CORS, Pino logging, Zod validation, rate limiting, Jest + Supertest, ESLint, Prettier, and Husky.",
      "Monorepo with a dedicated docs website built on Next.js, fumadocs, and a custom Structural Grid design system.",
    ],
    liveLink: "https://pestjs.vercel.app",
    repo: "https://github.com/nabinkhair42/pest-js",
    techStack: [
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Node.js", icon: NodeJsIcon },
      { name: "Express", icon: ExpressJsIcon },
      { name: "Next.js", icon: NextJsIcon },
      { name: "NPM Package", icon: NpmIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Zod", icon: ZodIcon },
      { name: "Prisma", icon: PrismaIcon },
      { name: "Drizzle ORM", icon: DrizzleOrmIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Vercel", icon: VercelIcon },
    ],
  },
  {
    icon: "/projects/assets-man.svg",
    title: "Assets Man",
    tagline: "A self-hosted, open-source Google Drive alternative.",
    description: [
      "Privacy-first file management platform with your own S3-compatible storage backend.",
      "Full-featured file browser with instant search, rich previews for PDFs/images/code, and nested folder hierarchy.",
      "Secure sharing with public links, password protection, expiry dates, and configurable per-user storage quotas.",
      "OTP-based email authentication, drag-and-drop uploads, auto-generated thumbnails, and full dark mode support.",
    ],
    liveLink: "https://assets-man.nabinkhair.com.np",
    repo: "https://github.com/nabinkhair42/assets-man",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "PostgreSQL", icon: PostgresqlIcon },
      { name: "Drizzle ORM", icon: DrizzleOrmIcon },
      { name: "Express", icon: ExpressJsIcon },
      { name: "Turborepo", icon: TurborepoIcon },
      { name: "AWS S3", icon: AwsIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    icon: "/projects/better-form.svg",
    title: "Better Form",
    tagline: "DX-First Dynamic Form Builder for React & Next.js",
    description: [
      "A next-generation developer-first dynamic form builder for React and Next.js",
      "Build powerful forms with drag & drop, live preview, and code export functionality",
      "Type-safe form building with TypeScript, Zod validation, and React Hook Form integration",
      "Beautiful UI built with shadcn/ui components and Tailwind CSS",
    ],
    liveLink: "https://better-form.nabinkhair.com.np",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Zod", icon: ZodIcon },
      { name: "React Hook Form", icon: ReactHookFormIcon },
    ],
  },
  {
    icon: "/projects/fastly.png",
    title: "Fastly",
    tagline: "SaaS Starter Kit",
    description: [
      "A SaaS starter kit for solo developers and startups.",
      "JWT Based Authentication and Authorization.",
      "User Management Dashboard",
      "Image Uploading with Uploadthing",
      "Builtin Vercel Deployment",
    ],
    liveLink: "https://fastly.nabinkhair.com.np",
    repo: "https://github.com/nabinkhair42/fastly",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "MongoDB", icon: MongodbIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "React Query", icon: ReactQueryIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    icon: "/projects/vtheme.svg",
    title: "VTheme",
    tagline: "Perfect VS Code Theme",
    liveLink: "https://vthemes.nabinkhair.com.np/",
    repo: "https://github.com/nabinkhair42/vtheme",
    description: [
      "Over 1200+ active users worldwide.",
      "Carefully crafted colors that enhance coding experience and reduce eye strain.",
      "A professionally designed color theme based on advanced color theory principles.",
    ],
    techStack: [
      { name: "JSON", icon: JsonIcon },
      { name: "VS Code", icon: VscodeIcon },
    ],
  },
  {
    icon: "/projects/pro-mcp.svg",
    title: "Pro MCP",
    tagline: "Registry of MCP Servers",
    liveLink: "https://promcp.nabinkhair.com.np",
    description: [
      "Over 4200+ MCP servers listed from around the world.",
      "Custom Server Listing Website with auto scraping of server information.",
      "User can search and upload servers information",
      "User-friendly interface for easy navigation and access to server information.",
    ],
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "Python", icon: PythonIcon },
      { name: "JavaScript", icon: JavascriptIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
    ],
  },
  {
    icon: "/projects/nepali-educate.png",
    title: "Nepali Educate",
    tagline: "Online Learning Platform",
    description: [
      "An online learning platform offering a high quality study notes for students of grade  11 and 12",
      "User-friendly interface for easy navigation and access to study materials.",
      "Trusted by over 50,000 students across Nepal.",
      "Over 100k monthly visitors",
    ],
    liveLink: "https://nepalieducate.com",
    techStack: [
      { name: "Jquery", icon: JqueryIcon },
      { name: "Blogger", icon: BloggerIcon },
      { name: "Canva", icon: CanvaIcon },
    ],
  },

  {
    icon: "/projects/juju.png",
    title: "Juju Connect",
    tagline: "Your Story, Your Stage",
    liveLink: "https://jujuconnect.com",
    description: [
      "Wrote and designed the backend architecture for the platform.",
      "Hosted and deployed all services on AWS and Cloudflare.",
      "Tested and developed APIs using Postman",
      "Collaborated with cross-functional teams to define, design, and ship new features",
    ],
    techStack: [
      { name: "Node.js", icon: NodeJsIcon },
      { name: "Express.js", icon: ExpressJsIcon },
      { name: "MongoDB", icon: MongodbIcon },
      { name: "AWS", icon: AwsIcon },
      { name: "Cloudflare", icon: CloudflareIcon },
      { name: "Postman", icon: PostmanIcon },
    ],
  },
  {
    icon: "/projects/flow-mint.png",
    title: "FlowMint",
    tagline: "Diagrams Made Effortless",
    description: [
      "A powerful diagramming tool for understanding and visualizing complex ideas.",
      "Create diagrams from simple text prompts using Gemini AI",
      "Export diagrams in multiple formats including PNG, SVG",
      "User authentication and management with JWT",
    ],
    liveLink: "https://flow.nabinkhair.com.np",
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "MongoDB", icon: MongodbIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "React Query", icon: ReactQueryIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Stripe", icon: StripeIcon },
      { name: "Zod", icon: ZodIcon },
    ],
  },
  {
    icon: "https://yourgit.vercel.app/favicon.ico",
    title: "YourGit",
    tagline: "GitHub Profile Stats Summary",
    liveLink: "https://yourgit.vercel.app/",
    description: [
      "Visualize any GitHub profile's contribution stats in a clean, shareable summary card.",
      "Displays repos, stars, followers, and contribution streaks at a glance.",
    ],
    techStack: [
      { name: "Next.js", icon: NextJsIcon },
      { name: "TypeScript", icon: TypescriptIcon },
      { name: "Tailwind CSS", icon: TailwindCssIcon },
      { name: "Vercel", icon: VercelIcon },
      { name: "shadcn/ui", icon: ShadcnUiIcon },
      { name: "Stripe", icon: StripeIcon },
    ],
  },
];
