import {
  Astro,
  AwsIcon,
  BashIcon,
  BetterAuth,
  CloudflareIcon,
  Docker,
  DrizzleOrmIcon,
  ExpressJsIcon,
  FastAPI,
  FigmaIcon,
  JavascriptIcon,
  ModelContextProtocol,
  MongodbIcon,
  NestjsIcon,
  NextJsIcon,
  NodeJsIcon,
  PostgresqlIcon,
  PrismaIcon,
  PythonIcon,
  Railway,
  ReactIcon,
  ReactQueryIcon,
  Redis,
  ShadcnUiIcon,
  SupabaseIcon,
  TailwindCssIcon,
  TurborepoIcon,
  ZodIcon,
  ZustandIcon,
} from "@/icons/tech";
import type { TechStack } from "@/types";

export const TechStacksList: TechStack[] = [
  { name: "AWS", icon: AwsIcon },
  { name: "Astro", icon: Astro },
  { name: "Bash", icon: BashIcon },
  { name: "Better Auth", icon: BetterAuth },
  { name: "Cloudflare", icon: CloudflareIcon },
  { name: "Docker", icon: Docker },
  { name: "Drizzle", icon: DrizzleOrmIcon },
  { name: "Express.js", icon: ExpressJsIcon },
  { name: "FastAPI", icon: FastAPI },
  { name: "Figma", icon: FigmaIcon },
  { name: "JavaScript", icon: JavascriptIcon },
  { name: "MCP", icon: ModelContextProtocol },
  { name: "MongoDB", icon: MongodbIcon },
  { name: "Next.js", icon: NextJsIcon },
  { name: "Nest.js", icon: NestjsIcon },
  { name: "Node.js", icon: NodeJsIcon },
  { name: "PostgreSQL", icon: PostgresqlIcon },
  { name: "Python", icon: PythonIcon },
  { name: "Prisma", icon: PrismaIcon },
  { name: "Railway", icon: Railway },
  { name: "React.js", icon: ReactIcon },
  { name: "TanStack Query", icon: ReactQueryIcon },
  { name: "Redis", icon: Redis },
  { name: "shadcn/ui", icon: ShadcnUiIcon },
  { name: "Supabase", icon: SupabaseIcon },
  { name: "Tailwind", icon: TailwindCssIcon },
  { name: "Turborepo", icon: TurborepoIcon },
  { name: "Zod", icon: ZodIcon },
  { name: "Zustand", icon: ZustandIcon },
];
