import {
  Anthropic,
  AwsIcon,
  BashIcon,
  BetterAuth,
  CloudflareIcon,
  CppIcon,
  Docker,
  DrizzleOrmIcon,
  ExpressJsIcon,
  FastAPI,
  FigmaIcon,
  GeminiIcon,
  GithubIcon,
  JavascriptIcon,
  ModelContextProtocol,
  MongodbIcon,
  NestjsIcon,
  NextJsIcon,
  OpenaiIcon,
  PerplexityAI,
  Playwright,
  PostgresqlIcon,
  PrismaIcon,
  Railway,
  ReactIcon,
  ReactQueryIcon,
  Redis,
  ShadcnUiIcon,
  SupabaseIcon,
  TailwindCssIcon,
  TypescriptIcon,
  VercelIcon,
  VertexAiIcon,
  ZodIcon,
  ZustandIcon,
} from "@/icons/tech";
import type { TechStack } from "@/types";

export const TechStacksList: TechStack[] = [
  { name: "AWS", icon: AwsIcon },
  { name: "Bash", icon: BashIcon },
  { name: "Better Auth", icon: BetterAuth },
  { name: "C++", icon: CppIcon },
  { name: "Claude", icon: Anthropic },
  { name: "Cloudflare", icon: CloudflareIcon },
  { name: "Docker", icon: Docker },
  { name: "Drizzle", icon: DrizzleOrmIcon },
  { name: "Express.js", icon: ExpressJsIcon },
  { name: "FastAPI", icon: FastAPI },
  { name: "Figma", icon: FigmaIcon },
  { name: "Gemini", icon: GeminiIcon },
  { name: "GitHub", icon: GithubIcon },
  { name: "JavaScript", icon: JavascriptIcon },
  { name: "MCP", icon: ModelContextProtocol },
  { name: "MongoDB", icon: MongodbIcon },
  { name: "Next.js", icon: NextJsIcon },
  { name: "Nest.js", icon: NestjsIcon },
  { name: "OpenAI", icon: OpenaiIcon },
  { name: "Perplexity", icon: PerplexityAI },
  { name: "Playwright", icon: Playwright },
  { name: "PostgreSQL", icon: PostgresqlIcon },
  { name: "Prisma", icon: PrismaIcon },
  { name: "Railway", icon: Railway },
  { name: "React.js", icon: ReactIcon },
  { name: "TanStack Query", icon: ReactQueryIcon },
  { name: "Redis", icon: Redis },
  { name: "shadcn/ui", icon: ShadcnUiIcon },
  { name: "Supabase", icon: SupabaseIcon },
  { name: "Tailwind", icon: TailwindCssIcon },
  { name: "TypeScript", icon: TypescriptIcon },
  { name: "Vercel", icon: VercelIcon },
  { name: "Vertex AI", icon: VertexAiIcon },
  { name: "Zod", icon: ZodIcon },
  { name: "Zustand", icon: ZustandIcon },
];
