import {
  AwsIcon,
  BashIcon,
  CloudflareIcon,
  CppIcon,
  ExpressJsIcon,
  FigmaIcon,
  GitIcon,
  GithubIcon,
  JavascriptIcon,
  JqueryIcon,
  MongodbIcon,
  NextJsIcon,
  PostgresqlIcon,
  PostmanIcon,
  PrismaIcon,
  ReactIcon,
  ReactQueryIcon,
  ShadcnUiIcon,
  TailwindCssIcon,
  TypescriptIcon,
  VercelIcon,
  ViteJsIcon,
  ZodIcon,
  ZustandIcon,
} from "@/icons/tech";
import type { TechStack } from "@/types";

export const TechStacksList: TechStack[] = [
  { name: "AWS", icon: AwsIcon },
  { name: "Bash", icon: BashIcon },
  { name: "C++", icon: CppIcon },
  { name: "Cloudflare", icon: CloudflareIcon },
  { name: "Express.js", icon: ExpressJsIcon },
  { name: "Figma", icon: FigmaIcon },
  { name: "Git", icon: GitIcon },
  { name: "GitHub", icon: GithubIcon },
  { name: "JQuery", icon: JqueryIcon },
  { name: "JavaScript", icon: JavascriptIcon },
  { name: "MongoDB", icon: MongodbIcon },
  { name: "Next.js", icon: NextJsIcon },
  // { name: "OpenAI", icon: OpenaiIcon },
  { name: "PostgreSQL", icon: PostgresqlIcon },
  { name: "Postman", icon: PostmanIcon },
  { name: "Prisma", icon: PrismaIcon },
  { name: "React.js", icon: ReactIcon },
  { name: "R. Query", icon: ReactQueryIcon },
  { name: "shadcn/ui", icon: ShadcnUiIcon },
  { name: "Tailwind", icon: TailwindCssIcon },
  { name: "TypeScript", icon: TypescriptIcon },
  { name: "Vercel", icon: VercelIcon },
  { name: "Vite", icon: ViteJsIcon },
  { name: "Zod", icon: ZodIcon },
  { name: "Zustand", icon: ZustandIcon },
];
